title: Data for Greece
description: Aνακάλυψε την Ελλάδα μέσα από δεδομένα
baseurl: "" # Base URL (e.g., /blog if hosted at example.com/blog)
url: "https://dataforgreece.com"
author: DataForGreece
email: support@justdataplease.com

# Define two separate blog collections for Greek and English posts
collections:
  en_posts:
    output: true
    permalink: /en/posts/:slug/
    relative_directory: en/_posts
  gr_posts:
    output: true
    permalink: /posts/:slug/
    relative_directory: gr/_posts

# Default language setting for posts in different directories
defaults:
  - scope:
      path: "en/_posts"
    values:
      lang: "en"
      layout: "post"
      categories: "blog"
      permalink: /en/posts/:slug/
  - scope:
      path: "gr/_posts"
    values:
      lang: "gr"
      layout: "post"
      categories: "blog"
      permalink: /posts/:slug/

languages:
  default: "gr"
  en:
    label: "English"
    path: "/en"

permalink: pretty
