title: Data for Greece
description: Aνακάλυψε την Ελλάδα μέσα από δεδομένα
baseurl: "" # Base URL (e.g., /blog if hosted at example.com/blog)
url: "https://dataforgreece.com"
author: DataForGreece
email: support@justdataplease.com
include: ['_reports/en','_reports/gr','_articles/en','_articles/gr','_data_directory/en','_data_directory/gr']

collections:
  articles:
    output: true
  reports:
    output: true
  data_directory:
    output: true

defaults:
  - scope:
      path: "_articles/en"
    values:
      lang: "en"
      layout: "post"
      permalink: /en/blog/:slug/
  - scope:
      path: "_articles/gr"
    values:
      lang: "gr"
      layout: "post"
      permalink: /blog/:slug/
  - scope:
      path: "_reports/en"
    values:
      lang: "en"
      layout: "report"
      categories: "reports"
      permalink: /en/reports/:slug/
  - scope:
      path: "_reports/gr"
    values:
      lang: "gr"
      layout: "report"
      categories: "reports"
      permalink: /reports/:slug/
  - scope:
      path: "_data_directory/en"
    values:
      lang: "en"
      layout: "data"
      categories: "data-directory"
      permalink: /en/data-directory/:slug/
  - scope:
      path: "_data_directory/gr"
    values:
      lang: "gr"
      layout: "data"
      categories: "data-directory"
      permalink: /data-directory/:slug/

languages:
  default: "gr"
  en:
    label: "English"
    path: "/en"

permalink: pretty
