title: Data for Greece
description: Aνακάλυψε την Ελλάδα μέσα από δεδομένα
baseurl: "" # Base URL (e.g., /blog if hosted at example.com/blog)
url: "https://dataforgreece.com"
author: DataForGreece
email: support@justdataplease.com
include: ['_reports/en','_reports/gr','_posts/en','_posts/gr','_data_dir/en','_data_dir/gr']

collections:
  posts:
    output: true
  reports:
    output: true

defaults:
  - scope:
      path: "en/_posts"
    values:
      lang: "_posts/en"
      layout: "post"
      categories: "blog"
      permalink: /en/blog/:slug/
  - scope:
      path: "_posts/gr"
    values:
      lang: "gr"
      layout: "post"
      categories: "blog"
      permalink: /blog/:slug/
  - scope:
      path: "_reports/en"
    values:
      lang: "en"
      layout: "report"
      categories: "reports"
      permalink: /en/reports/:slug/
  - scope:
      path: "_reports/gr"
    values:
      lang: "gr"
      layout: "report"
      categories: "reports"
      permalink: /reports/:slug/

languages:
  default: "gr"
  en:
    label: "English"
    path: "/en"

permalink: pretty
